# Generated by Django 2.1.7 on 2019-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20181211_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
    ]
